/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/request-otp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Otp */
    post: operations["request_otp_api_auth_request_otp_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify Otp */
    post: operations["verify_otp_api_auth_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/token/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Current User */
    get: operations["get_current_user_api_auth_token_verify_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/token/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Token */
    post: operations["refresh_token_api_auth_token_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/articles/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Articles */
    get: operations["get_articles_api_articles__get"];
    put?: never;
    /** Create Article */
    post: operations["create_article_api_articles__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/articles/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Article */
    get: operations["get_article_api_articles__id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Article */
    patch: operations["update_article_api_articles__id__patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Article */
    Article: {
      /** Title */
      title: string;
      /** Content */
      content: string;
      /** Scheduled Date */
      scheduled_date?: string | null;
      /** Archived Date */
      archived_date?: string | null;
      /** Id */
      id: number;
    };
    /** ArticleCreate */
    ArticleCreate: {
      /** Title */
      title: string;
      /** Content */
      content: string;
      /** Scheduled Date */
      scheduled_date?: string | null;
      /** Archived Date */
      archived_date?: string | null;
    };
    /** ArticleUpdate */
    ArticleUpdate: {
      /** Archive */
      archive: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** OneTimeCodeInput */
    OneTimeCodeInput: {
      /** Phone Number */
      phone_number: string;
    };
    /** RefreshTokenSchema */
    RefreshTokenSchema: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** TokenPair */
    TokenPair: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerifyCodeInput */
    VerifyCodeInput: {
      /** Phone Number */
      phone_number: string;
      /** Name */
      name?: string | null;
      /** Code */
      code: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  request_otp_api_auth_request_otp_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OneTimeCodeInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_otp_api_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyCodeInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_current_user_api_auth_token_verify_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  refresh_token_api_auth_token_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_articles_api_articles__get: {
    parameters: {
      query: {
        status: "scheduled" | "published" | "archived";
        limit?: unknown;
        offset?: unknown;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["Article"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_article_api_articles__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_article_api_articles__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_article_api_articles__id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticleUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
