/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/request-otp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Otp */
    post: operations["request_otp_api_auth_request_otp_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify Otp */
    post: operations["verify_otp_api_auth_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/token/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Current User */
    get: operations["get_current_user_api_auth_token_verify_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/token/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Token */
    post: operations["refresh_token_api_auth_token_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trips/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Trips */
    get: operations["get_trips_api_trips__get"];
    put?: never;
    /** Create Trip */
    post: operations["create_trip_api_trips__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trips/ws/client": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Demo Page */
    get: operations["get_demo_page_api_trips_ws_client_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** OneTimeCodeInput */
    OneTimeCodeInput: {
      /** Phone Number */
      phone_number: string;
    };
    /** RefreshTokenSchema */
    RefreshTokenSchema: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** TokenPair */
    TokenPair: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
    };
    /** TripCreate */
    TripCreate: {
      role: components["schemas"]["TripRole"];
      type: components["schemas"]["TripType"] | null;
      /** Origin */
      origin: string;
      /** Destination */
      destination: string;
      /**
       * Departure Date
       * Format: date
       */
      departure_date: string;
      /** Departure Time */
      departure_time: string | null;
      /** Departure Now */
      departure_now: boolean;
      /** Number Of People */
      number_of_people: number;
      /** Suggested Price */
      suggested_price: number | null;
      /** Comment */
      comment: string | null;
    };
    /** TripResponse */
    TripResponse: {
      role: components["schemas"]["TripRole"];
      type: components["schemas"]["TripType"] | null;
      /** Origin */
      origin: string;
      /** Destination */
      destination: string;
      /**
       * Departure Date
       * Format: date
       */
      departure_date: string;
      /** Departure Time */
      departure_time: string | null;
      /** Departure Now */
      departure_now: boolean;
      /** Number Of People */
      number_of_people: number;
      /** Suggested Price */
      suggested_price: number | null;
      /** Comment */
      comment: string | null;
      /** Id */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Active */
      active: boolean;
      /** User Id */
      user_id: string;
    };
    /**
     * TripRole
     * @enum {string}
     */
    TripRole: "driver" | "passenger";
    /**
     * TripType
     * @enum {string}
     */
    TripType: "salon" | "hitch_ride" | "delivery";
    /** User */
    User: {
      /** Id */
      id: string;
      /** Name */
      name?: string | null;
      /** Phone Number */
      phone_number: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerifyCodeInput */
    VerifyCodeInput: {
      /** Phone Number */
      phone_number: string;
      /** Name */
      name?: string | null;
      /** Code */
      code: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  request_otp_api_auth_request_otp_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OneTimeCodeInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_otp_api_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyCodeInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_current_user_api_auth_token_verify_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  refresh_token_api_auth_token_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_trips_api_trips__get: {
    parameters: {
      query?: {
        cursor_date?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TripResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_trip_api_trips__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TripCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_demo_page_api_trips_ws_client_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
